version: '3'

services:
  epitomeDb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${EXPOSE_MYSQL_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./epitome_pyBackend:/app/epitome_pyBackend
      - ./kling_server:/app/kling_server
      - ./smart_teaching_server:/app/smart_teaching_server
      - ./media_root:/app/media_root
      - ./static_dirs:/app/static_dirs
      - ./static_root:/app/static_root
    ports:
      - "8000"
    command: >
      sh -c "sleep 10 && 
      python manage.py collectstatic --noinput && 
      gunicorn --bind :8000 epitome_pyBackend.wsgi:application"
    environment:
      - DB_HOST=epitomeDb
      - DB_PORT=3306
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "sleep 20 && \
      python manage.py makemigrations --noinput && \
      python manage.py migrate --noinput"
    environment:
      - DB_HOST=epitomeDb
      - DB_PORT=3306
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  nginx:
    image: nginx:latest
    ports:
      - "${EXPOSE_WEB_PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./media_root:/media
      - ./static_root:/static
    depends_on:
      - web  # 简单依赖声明

volumes:
  db_data: