# Generated by Django 5.2 on 2025-04-08 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kling_server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermedia',
            name='image_files',
        ),
        migrations.RemoveField(
            model_name='usermedia',
            name='video_files',
        ),
        migrations.CreateModel(
            name='UserMediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10)),
                ('file_url', models.URLField()),
                ('file_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_name', models.CharField(max_length=100)),
                ('prompt', models.TextField()),
                ('task_id', models.CharField(max_length=100, unique=True)),
                ('user_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='kling_server.usermedia')),
            ],
        ),
    ]
