# Generated by Django 5.2 on 2025-04-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kling_server', '0002_remove_usermedia_image_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermediafile',
            name='task_status',
            field=models.CharField(default='submitted', max_length=20),
        ),
    ]
